name: Continuous integration
on: push

env:
  GODOT_VERSION: 3.4.2
  EXPORT_NAME: escape-space

jobs:
  export-windows:
    name: Export (Windows)
    runs-on: ubuntu-20.04
    container:
      image: abarichello/godot-ci:4.3-stable
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        run: |
          mkdir -p ~/.local/share/godot/templates/
          mv /root/.local/share/godot/templates/$GODOT_VERSION.stable ~/.local/share/godot/templates/$GODOT_VERSION.stable
      - name: Export (Windows)
        run: |
          mkdir -p dist/
          godot -v --export "Windows Desktop" "dist/$EXPORT_NAME.exe"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.EXPORT_NAME }}-windows
          path: dist          
